A custom HDK operator example with an option to reload changes at runtime, to retain the state of the loaded scene.

** Build:
Update CMake to point to Houdini installation directory ($HFS).
The `make install` copies the host shared library to the dso folder inside $HOME/houdini18.0. The guest plugin is currently not copied. (see notes below)
#+BEGIN_SRC 
mkdir __build
cd __build
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/houdini18.0/dso
make install
#+END_SRC

** NOTES:
Houdini OP_OperatorTable - does not handle reloading same dso files. Once path is loaded there is no easy way (that I know of) to dealocate it. A dumb workaround is to on every build increase the dso file name and tell Houdini to load the latest .so (containing same symbols) and override existing operator (OP_Operator). This should do the 'reload' trick and update operator in the current session with the recent changes.
IMPORTANT: Between every Houdini restart - make sure to remove all generated temporary dsos (*.so) in the build directory. This is necessary to register the dso reload callback only once. 
** TODO:
- move all the globals into VersionCounter singleton
- extract base_name of the file (without Boost)
